import type { ComponentType } from 'react';
import type { LocaleCode } from '@/lib/i18n/types';

type MDXModule = { default: ComponentType<any> };

/** English MDX articles (default). Keys are reading slugs. */
const mdxMapEn: Record<string, () => Promise<MDXModule>> = {
  'menger-principles-of-economics': () => import('@/content/level-1/menger-principles-of-economics.mdx'),
  'stigler-theory-of-price': () => import('@/content/level-1/stigler-theory-of-price.mdx'),
  'smith-wealth-of-nations': () => import('@/content/level-1/smith-wealth-of-nations.mdx'),
  'business-history-of-finance': () => import('@/content/level-1/business-history-of-finance.mdx'),
  'buffett-shareholder-letters': () => import('@/content/level-2/buffett-shareholder-letters.mdx'),
  'fisher-common-stocks': () => import('@/content/level-2/fisher-common-stocks.mdx'),
  'marks-oaktree-memos': () => import('@/content/level-2/marks-oaktree-memos.mdx'),
  'livermore-reminiscences': () => import('@/content/level-2/livermore-reminiscences.mdx'),
  'druckenmiller-principles': () => import('@/content/level-2/druckenmiller-principles.mdx'),
  'graham-value-investing': () => import('@/content/level-2/graham-value-investing.mdx'),
  'engines-that-move-markets': () => import('@/content/level-2/engines-that-move-markets.mdx'),
  'lynch-one-up-on-wall-street': () => import('@/content/level-2/lynch-one-up-on-wall-street.mdx'),
  'tudor-jones-principles': () => import('@/content/level-2/tudor-jones-principles.mdx'),
  'schwager-market-wizards': () => import('@/content/level-2/schwager-market-wizards.mdx'),
  'taleb-incerto': () => import('@/content/level-2/taleb-incerto.mdx'),
  'keynes-general-theory': () => import('@/content/level-3/keynes-general-theory.mdx'),
  'hayek-prices-and-production': () => import('@/content/level-3/hayek-prices-and-production.mdx'),
  'soros-reflexivity': () => import('@/content/level-3/soros-reflexivity.mdx'),
  'behavioral-finance': () => import('@/content/level-3/behavioral-finance.mdx'),
  'friedman-monetary-theory': () => import('@/content/level-3/friedman-monetary-theory.mdx'),
  'damodaran-little-book-valuation': () => import('@/content/level-4/damodaran-little-book-valuation.mdx'),
  'growth-investing-principles': () => import('@/content/level-4/growth-investing-principles.mdx'),
  'technical-analysis': () => import('@/content/level-4/technical-analysis.mdx'),
  'quant-foundations': () => import('@/content/level-5/quant-foundations.mdx'),
  'econometrics-and-fx': () => import('@/content/level-5/econometrics-and-fx.mdx'),
  'garch-101': () => import('@/content/level-5/garch-101.mdx'),
  'portfolio-construction': () => import('@/content/level-6/portfolio-construction.mdx'),
  'theory-to-application': () => import('@/content/level-6/theory-to-application.mdx'),
  'systematic-indices': () => import('@/content/level-6/systematic-indices.mdx'),
  'gappy-lecture-1-alpha-research': () => import('@/content/level-6/gappy-lecture-1-alpha-research.mdx'),
  'gappy-lecture-2-factor-models': () => import('@/content/level-6/gappy-lecture-2-factor-models.mdx'),
  'gappy-lecture-3-factor-evaluation': () => import('@/content/level-6/gappy-lecture-3-factor-evaluation.mdx'),
  'physical-financial-commodities': () => import('@/content/level-7/physical-financial-commodities.mdx'),
  'model-implementation': () => import('@/content/level-7/model-implementation.mdx'),
  'derivative-portfolio-management': () => import('@/content/level-7/derivative-portfolio-management.mdx'),
  'fixed-income-fundamentals': () => import('@/content/level-7/fixed-income-fundamentals.mdx'),
  'market-microstructure-trading': () => import('@/content/level-8/market-microstructure-trading.mdx'),
  'stochastic-volatility-models': () => import('@/content/level-8/stochastic-volatility-models.mdx'),
  'differential-machine-learning': () => import('@/content/level-8/differential-machine-learning.mdx'),
  'quasi-random-number-generation': () => import('@/content/level-8/quasi-random-number-generation.mdx'),
};

/**
 * Locale-specific MDX loaders. Forks add translated articles here, e.g.:
 *   'zh-CN': { 'menger-principles-of-economics': () => import('@/content/zh-CN/level-1/...') }
 * Missing locale or slug falls back to English.
 */
const localeMdxMap: Record<LocaleCode, Record<string, () => Promise<MDXModule>>> = {
  en: mdxMapEn,
  'zh-HK': {
    'menger-principles-of-economics':    () => import('@/content/zh-HK/level-1/menger-principles-of-economics.mdx'),
    'stigler-theory-of-price':           () => import('@/content/zh-HK/level-1/stigler-theory-of-price.mdx'),
    'smith-wealth-of-nations':           () => import('@/content/zh-HK/level-1/smith-wealth-of-nations.mdx'),
    'business-history-of-finance':       () => import('@/content/zh-HK/level-1/business-history-of-finance.mdx'),
    'buffett-shareholder-letters':       () => import('@/content/zh-HK/level-2/buffett-shareholder-letters.mdx'),
    'fisher-common-stocks':              () => import('@/content/zh-HK/level-2/fisher-common-stocks.mdx'),
    'marks-oaktree-memos':               () => import('@/content/zh-HK/level-2/marks-oaktree-memos.mdx'),
    'livermore-reminiscences':           () => import('@/content/zh-HK/level-2/livermore-reminiscences.mdx'),
    'druckenmiller-principles':          () => import('@/content/zh-HK/level-2/druckenmiller-principles.mdx'),
    'graham-value-investing':            () => import('@/content/zh-HK/level-2/graham-value-investing.mdx'),
    'engines-that-move-markets':         () => import('@/content/zh-HK/level-2/engines-that-move-markets.mdx'),
    'lynch-one-up-on-wall-street':       () => import('@/content/zh-HK/level-2/lynch-one-up-on-wall-street.mdx'),
    'tudor-jones-principles':            () => import('@/content/zh-HK/level-2/tudor-jones-principles.mdx'),
    'schwager-market-wizards':           () => import('@/content/zh-HK/level-2/schwager-market-wizards.mdx'),
    'taleb-incerto':                     () => import('@/content/zh-HK/level-2/taleb-incerto.mdx'),
    'keynes-general-theory':             () => import('@/content/zh-HK/level-3/keynes-general-theory.mdx'),
    'hayek-prices-and-production':       () => import('@/content/zh-HK/level-3/hayek-prices-and-production.mdx'),
    'soros-reflexivity':                 () => import('@/content/zh-HK/level-3/soros-reflexivity.mdx'),
    'behavioral-finance':                () => import('@/content/zh-HK/level-3/behavioral-finance.mdx'),
    'friedman-monetary-theory':          () => import('@/content/zh-HK/level-3/friedman-monetary-theory.mdx'),
    'damodaran-little-book-valuation':   () => import('@/content/zh-HK/level-4/damodaran-little-book-valuation.mdx'),
    'growth-investing-principles':       () => import('@/content/zh-HK/level-4/growth-investing-principles.mdx'),
    'technical-analysis':                () => import('@/content/zh-HK/level-4/technical-analysis.mdx'),
    'quant-foundations':                 () => import('@/content/zh-HK/level-5/quant-foundations.mdx'),
    'econometrics-and-fx':               () => import('@/content/zh-HK/level-5/econometrics-and-fx.mdx'),
    'garch-101':                         () => import('@/content/zh-HK/level-5/garch-101.mdx'),
    'portfolio-construction':            () => import('@/content/zh-HK/level-6/portfolio-construction.mdx'),
    'theory-to-application':             () => import('@/content/zh-HK/level-6/theory-to-application.mdx'),
    'systematic-indices':                () => import('@/content/zh-HK/level-6/systematic-indices.mdx'),
    'gappy-lecture-1-alpha-research':    () => import('@/content/zh-HK/level-6/gappy-lecture-1-alpha-research.mdx'),
    'gappy-lecture-2-factor-models':     () => import('@/content/zh-HK/level-6/gappy-lecture-2-factor-models.mdx'),
    'gappy-lecture-3-factor-evaluation': () => import('@/content/zh-HK/level-6/gappy-lecture-3-factor-evaluation.mdx'),
    'physical-financial-commodities':    () => import('@/content/zh-HK/level-7/physical-financial-commodities.mdx'),
    'model-implementation':              () => import('@/content/zh-HK/level-7/model-implementation.mdx'),
    'derivative-portfolio-management':   () => import('@/content/zh-HK/level-7/derivative-portfolio-management.mdx'),
    'fixed-income-fundamentals':         () => import('@/content/zh-HK/level-7/fixed-income-fundamentals.mdx'),
    'market-microstructure-trading':     () => import('@/content/zh-HK/level-8/market-microstructure-trading.mdx'),
    'stochastic-volatility-models':      () => import('@/content/zh-HK/level-8/stochastic-volatility-models.mdx'),
    'differential-machine-learning':     () => import('@/content/zh-HK/level-8/differential-machine-learning.mdx'),
    'quasi-random-number-generation':    () => import('@/content/zh-HK/level-8/quasi-random-number-generation.mdx'),
  },
  'zh-TW': {
    'menger-principles-of-economics':    () => import('@/content/zh-TW/level-1/menger-principles-of-economics.mdx'),
    'stigler-theory-of-price':           () => import('@/content/zh-TW/level-1/stigler-theory-of-price.mdx'),
    'smith-wealth-of-nations':           () => import('@/content/zh-TW/level-1/smith-wealth-of-nations.mdx'),
    'business-history-of-finance':       () => import('@/content/zh-TW/level-1/business-history-of-finance.mdx'),
    'buffett-shareholder-letters':       () => import('@/content/zh-TW/level-2/buffett-shareholder-letters.mdx'),
    'fisher-common-stocks':              () => import('@/content/zh-TW/level-2/fisher-common-stocks.mdx'),
    'marks-oaktree-memos':               () => import('@/content/zh-TW/level-2/marks-oaktree-memos.mdx'),
    'livermore-reminiscences':           () => import('@/content/zh-TW/level-2/livermore-reminiscences.mdx'),
    'druckenmiller-principles':          () => import('@/content/zh-TW/level-2/druckenmiller-principles.mdx'),
    'graham-value-investing':            () => import('@/content/zh-TW/level-2/graham-value-investing.mdx'),
    'engines-that-move-markets':         () => import('@/content/zh-TW/level-2/engines-that-move-markets.mdx'),
    'lynch-one-up-on-wall-street':       () => import('@/content/zh-TW/level-2/lynch-one-up-on-wall-street.mdx'),
    'tudor-jones-principles':            () => import('@/content/zh-TW/level-2/tudor-jones-principles.mdx'),
    'schwager-market-wizards':           () => import('@/content/zh-TW/level-2/schwager-market-wizards.mdx'),
    'taleb-incerto':                     () => import('@/content/zh-TW/level-2/taleb-incerto.mdx'),
    'keynes-general-theory':             () => import('@/content/zh-TW/level-3/keynes-general-theory.mdx'),
    'hayek-prices-and-production':       () => import('@/content/zh-TW/level-3/hayek-prices-and-production.mdx'),
    'soros-reflexivity':                 () => import('@/content/zh-TW/level-3/soros-reflexivity.mdx'),
    'behavioral-finance':                () => import('@/content/zh-TW/level-3/behavioral-finance.mdx'),
    'friedman-monetary-theory':          () => import('@/content/zh-TW/level-3/friedman-monetary-theory.mdx'),
    'damodaran-little-book-valuation':   () => import('@/content/zh-TW/level-4/damodaran-little-book-valuation.mdx'),
    'growth-investing-principles':       () => import('@/content/zh-TW/level-4/growth-investing-principles.mdx'),
    'technical-analysis':                () => import('@/content/zh-TW/level-4/technical-analysis.mdx'),
    'quant-foundations':                 () => import('@/content/zh-TW/level-5/quant-foundations.mdx'),
    'econometrics-and-fx':               () => import('@/content/zh-TW/level-5/econometrics-and-fx.mdx'),
    'garch-101':                         () => import('@/content/zh-TW/level-5/garch-101.mdx'),
    'portfolio-construction':            () => import('@/content/zh-TW/level-6/portfolio-construction.mdx'),
    'theory-to-application':             () => import('@/content/zh-TW/level-6/theory-to-application.mdx'),
    'systematic-indices':                () => import('@/content/zh-TW/level-6/systematic-indices.mdx'),
    'gappy-lecture-1-alpha-research':    () => import('@/content/zh-TW/level-6/gappy-lecture-1-alpha-research.mdx'),
    'gappy-lecture-2-factor-models':     () => import('@/content/zh-TW/level-6/gappy-lecture-2-factor-models.mdx'),
    'gappy-lecture-3-factor-evaluation': () => import('@/content/zh-TW/level-6/gappy-lecture-3-factor-evaluation.mdx'),
    'physical-financial-commodities':    () => import('@/content/zh-TW/level-7/physical-financial-commodities.mdx'),
    'model-implementation':              () => import('@/content/zh-TW/level-7/model-implementation.mdx'),
    'derivative-portfolio-management':   () => import('@/content/zh-TW/level-7/derivative-portfolio-management.mdx'),
    'fixed-income-fundamentals':         () => import('@/content/zh-TW/level-7/fixed-income-fundamentals.mdx'),
    'market-microstructure-trading':     () => import('@/content/zh-TW/level-8/market-microstructure-trading.mdx'),
    'stochastic-volatility-models':      () => import('@/content/zh-TW/level-8/stochastic-volatility-models.mdx'),
    'differential-machine-learning':     () => import('@/content/zh-TW/level-8/differential-machine-learning.mdx'),
    'quasi-random-number-generation':    () => import('@/content/zh-TW/level-8/quasi-random-number-generation.mdx'),
  },
  'zh-CN': {
    'menger-principles-of-economics':    () => import('@/content/zh-CN/level-1/menger-principles-of-economics.mdx'),
    'stigler-theory-of-price':           () => import('@/content/zh-CN/level-1/stigler-theory-of-price.mdx'),
    'smith-wealth-of-nations':           () => import('@/content/zh-CN/level-1/smith-wealth-of-nations.mdx'),
    'business-history-of-finance':       () => import('@/content/zh-CN/level-1/business-history-of-finance.mdx'),
    'buffett-shareholder-letters':       () => import('@/content/zh-CN/level-2/buffett-shareholder-letters.mdx'),
    'fisher-common-stocks':              () => import('@/content/zh-CN/level-2/fisher-common-stocks.mdx'),
    'marks-oaktree-memos':               () => import('@/content/zh-CN/level-2/marks-oaktree-memos.mdx'),
    'livermore-reminiscences':           () => import('@/content/zh-CN/level-2/livermore-reminiscences.mdx'),
    'druckenmiller-principles':          () => import('@/content/zh-CN/level-2/druckenmiller-principles.mdx'),
    'graham-value-investing':            () => import('@/content/zh-CN/level-2/graham-value-investing.mdx'),
    'engines-that-move-markets':         () => import('@/content/zh-CN/level-2/engines-that-move-markets.mdx'),
    'lynch-one-up-on-wall-street':       () => import('@/content/zh-CN/level-2/lynch-one-up-on-wall-street.mdx'),
    'tudor-jones-principles':            () => import('@/content/zh-CN/level-2/tudor-jones-principles.mdx'),
    'schwager-market-wizards':           () => import('@/content/zh-CN/level-2/schwager-market-wizards.mdx'),
    'taleb-incerto':                     () => import('@/content/zh-CN/level-2/taleb-incerto.mdx'),
    'keynes-general-theory':             () => import('@/content/zh-CN/level-3/keynes-general-theory.mdx'),
    'hayek-prices-and-production':       () => import('@/content/zh-CN/level-3/hayek-prices-and-production.mdx'),
    'soros-reflexivity':                 () => import('@/content/zh-CN/level-3/soros-reflexivity.mdx'),
    'behavioral-finance':                () => import('@/content/zh-CN/level-3/behavioral-finance.mdx'),
    'friedman-monetary-theory':          () => import('@/content/zh-CN/level-3/friedman-monetary-theory.mdx'),
    'damodaran-little-book-valuation':   () => import('@/content/zh-CN/level-4/damodaran-little-book-valuation.mdx'),
    'growth-investing-principles':       () => import('@/content/zh-CN/level-4/growth-investing-principles.mdx'),
    'technical-analysis':                () => import('@/content/zh-CN/level-4/technical-analysis.mdx'),
    'quant-foundations':                 () => import('@/content/zh-CN/level-5/quant-foundations.mdx'),
    'econometrics-and-fx':               () => import('@/content/zh-CN/level-5/econometrics-and-fx.mdx'),
    'garch-101':                         () => import('@/content/zh-CN/level-5/garch-101.mdx'),
    'portfolio-construction':            () => import('@/content/zh-CN/level-6/portfolio-construction.mdx'),
    'theory-to-application':             () => import('@/content/zh-CN/level-6/theory-to-application.mdx'),
    'systematic-indices':                () => import('@/content/zh-CN/level-6/systematic-indices.mdx'),
    'gappy-lecture-1-alpha-research':    () => import('@/content/zh-CN/level-6/gappy-lecture-1-alpha-research.mdx'),
    'gappy-lecture-2-factor-models':     () => import('@/content/zh-CN/level-6/gappy-lecture-2-factor-models.mdx'),
    'gappy-lecture-3-factor-evaluation': () => import('@/content/zh-CN/level-6/gappy-lecture-3-factor-evaluation.mdx'),
    'physical-financial-commodities':    () => import('@/content/zh-CN/level-7/physical-financial-commodities.mdx'),
    'model-implementation':              () => import('@/content/zh-CN/level-7/model-implementation.mdx'),
    'derivative-portfolio-management':   () => import('@/content/zh-CN/level-7/derivative-portfolio-management.mdx'),
    'fixed-income-fundamentals':         () => import('@/content/zh-CN/level-7/fixed-income-fundamentals.mdx'),
    'market-microstructure-trading':     () => import('@/content/zh-CN/level-8/market-microstructure-trading.mdx'),
    'stochastic-volatility-models':      () => import('@/content/zh-CN/level-8/stochastic-volatility-models.mdx'),
    'differential-machine-learning':     () => import('@/content/zh-CN/level-8/differential-machine-learning.mdx'),
    'quasi-random-number-generation':    () => import('@/content/zh-CN/level-8/quasi-random-number-generation.mdx'),
  },
};

const DEFAULT_MDX_LOCALE: LocaleCode = 'en';

export async function loadMDXContent(
  slug: string,
  locale: LocaleCode = DEFAULT_MDX_LOCALE
): Promise<ComponentType<any> | null> {
  const chain = [locale, DEFAULT_MDX_LOCALE];
  for (const code of chain) {
    const map = localeMdxMap[code];
    const loader = map?.[slug];
    if (!loader) continue;
    try {
      const mod = await loader();
      return mod.default;
    } catch {
      continue;
    }
  }
  return null;
}
